GOSM/Controllers/LoginViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GOSM.Models;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;
using Microsoft.AspNetCore.Http;
using System.IdentityModel.Tokens.Jwt;

namespace GOSM.Controllers
{
    public class LoginViewController : Controller
    {
        private string APIUri = "https://localhost:44366/api/Users/";

        public ViewResult Login() => View();

        [HttpPost]
        public async Task<IActionResult> Login(AuthenticateRequest login)
        {
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(login), Encoding.UTF8, "application/json");
                using (var response = await httpClient.PostAsync("https://localhost:44366/api/Authentication/authenticate", content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.BadRequest)
                    {
                        ViewBag.Result = "BadReq";
                    }
                    else if(response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        login = JsonConvert.DeserializeObject<AuthenticateRequest>(apiResponse);

                        var loginResponse = JsonConvert.DeserializeObject<AuthenticateResponse>(apiResponse);
                        setTokenCookie(loginResponse.JwtToken, loginResponse.Username);
                        HttpContext.Session.SetString("Username", loginResponse.Username);
                        return RedirectToAction("Index", "Home");
                    }
                    
                }
            }
            return View(login);
        }

        public ViewResult Register() => View();

        [HttpPost]
        public async Task<IActionResult> Register(User register)
        {
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(register), Encoding.UTF8, "application/json");
                using (var response = await httpClient.PostAsync(APIUri, content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    //register = JsonConvert.DeserializeObject<User>(apiResponse);
                    
                    if (response.StatusCode == System.Net.HttpStatusCode.BadRequest)
                    {
                        ViewBag.Result = "BadReq";
                    }
                    else if (response.StatusCode == System.Net.HttpStatusCode.Created)
                    {
                        ViewBag.Result = "Created";
                        return RedirectToAction("Index", "Home");
                    }
                    else if (response.StatusCode == System.Net.HttpStatusCode.Conflict)
                    {
                        ViewBag.Result = "Conflict";
                    }
                }
            }
            return View(register);
        }

        private void setTokenCookie(string token, string username)
        {
            var cookieOptions = new CookieOptions
            {
                HttpOnly = false
                //Expires = DateTime.UtcNow.AddDays(7)
            };
            Response.Cookies.Append("jwtToken", token, cookieOptions);
            Response.Cookies.Append("Username", username, cookieOptions);
        }
    }
}

GOSM/Controllers/PostViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GOSM.Models;
using System.Net.Http;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Text;

namespace GOSM.Controllers
{
    public class PostViewController : Controller
    {
        private string APIUri = "https://localhost:44366/api/Posts/";

        public async Task<IActionResult> PostList()
        {
            List<Post> postList = new List<Post>();
            using (var httpClient = new HttpClient())
            {
                var username = PassTokenToHeader(httpClient);

                using (var response = await httpClient.GetAsync(APIUri))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.Unauthorized)
                    {
                        RedirectToAction("Index", "Home");
                    }
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    postList = JsonConvert.DeserializeObject<List<Post>>(apiResponse);
                }
                
            }

            return View(postList);
        }

        [HttpPost]
        public async Task<IActionResult> CreateComment(int id, string comment)
        {
            Comment reqComment = new Comment();
            Post reqPost = new Post();
            using (var httpClient = new HttpClient())
            {
                var username = PassTokenToHeader(httpClient);
                using (var response = await httpClient.GetAsync(APIUri + id))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.Unauthorized)
                    {
                        RedirectToAction("Index", "Home");
                    }
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    reqPost = JsonConvert.DeserializeObject<Post>(apiResponse);
                }
                reqComment.Text = comment;
                reqComment.UserID = reqPost.UserID;
                reqComment.PostID = id;
                StringContent content = new StringContent(JsonConvert.SerializeObject(reqComment), Encoding.UTF8, "application/json");
                using (var response = await httpClient.PostAsync(APIUri + id + "/Comments", content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.Unauthorized)
                    {
                        RedirectToAction("Index", "Home");
                    }
                }
            }
            return RedirectToAction("PostList");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteComment(int postId, int commentId)
        {
            using (var httpClient = new HttpClient())
            {
                PassTokenToHeader(httpClient);
                using (var response = await httpClient.DeleteAsync(APIUri + postId + "/Comments/" + commentId))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();

                }
            }
            return RedirectToAction("PostList");
        }

        public string PassTokenToHeader(HttpClient httpClient)
        {
            string username = "";
            var token = HttpContext.Request.Cookies.FirstOrDefault(c => c.Key == "jwtToken").Value;
            if (token != null)
            {
                JwtSecurityTokenHandler handler = new JwtSecurityTokenHandler();
                JwtSecurityToken tok = handler.ReadJwtToken(token);
                username = tok.Claims.FirstOrDefault(t => t.Type == "Username")?.Value;
                //ViewBag.Auth = username;
            }
            httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);
            return username;
        }
    }
}

GOSM/Controllers/UserViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GOSM.Models;
using System.Net.Http;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Text;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GOSM.Controllers
{
    public class UserViewController : Controller
    {
        private string APIUri = "https://localhost:44366/api/Users/";
        public async Task<IActionResult> UserList()
        {

            List<User> userList = new List<User>();
            using (var httpClient = new HttpClient())
            {
                var username = PassTokenToHeader(httpClient);
                
                using (var response = await httpClient.GetAsync(APIUri))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.Unauthorized)
                    {
                        RedirectToAction("Index", "Home");
                    }
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    userList = JsonConvert.DeserializeObject<List<User>>(apiResponse);
                }
                if (username != "admin")
                {
                    User oneUser = new User();
                    oneUser = userList.FirstOrDefault(u => u.Username == username);
                    userList.Clear();
                    userList.Add(oneUser);
                }
            }

            return View(userList);
        }

        //public async Task<IActionResult> EditUser()
        //{

        //}

        public async Task<IActionResult> UserProfile(int id)
        {
            User user = new User();
            using (var httpClient = new HttpClient())
            {
                PassTokenToHeader(httpClient);
                using(var response = await httpClient.GetAsync(APIUri + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    user = JsonConvert.DeserializeObject<User>(apiResponse);
                }
            }
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> UserProfile(User user)
        {
            User returnUser = new User();
            using (var httpClient = new HttpClient())
            {
                PassTokenToHeader(httpClient);
                StringContent content = new StringContent(JsonConvert.SerializeObject(user), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PutAsync(APIUri + user.ID, content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    ViewBag.Result = "Success";
                    using (var getResponse = await httpClient.GetAsync(APIUri + user.ID))
                    {
                        apiResponse = await getResponse.Content.ReadAsStringAsync();
                        returnUser = JsonConvert.DeserializeObject<User>(apiResponse);
                    }

                }
            }
            return View(returnUser);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUser(int id)
        {
            using (var httpClient = new HttpClient())
            {
                PassTokenToHeader(httpClient);
                using (var response = await httpClient.DeleteAsync(APIUri + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction("UserList");
        }

        public async Task<IActionResult> UserAddGame()
        {
            List<RelevantGames> gamesList = new List<RelevantGames>();
            using (var httpClient = new HttpClient())
            {
                PassTokenToHeader(httpClient);

                using (var response = await httpClient.GetAsync("https://localhost:44366/api/RelevantGames"))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.Unauthorized)
                    {
                        RedirectToAction("Index", "Home");
                    }
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    gamesList = JsonConvert.DeserializeObject<List<RelevantGames>>(apiResponse);
                    ViewBag.GameID = new SelectList(gamesList, "ID", "Title");
                }
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UserAddGame(RelevantGames game)
        {
            RelevantGames relGame = new RelevantGames();
            List<User> userList = new List<User>();
            User user = new User();
            using (var httpClient = new HttpClient())
            {
                var username = PassTokenToHeader(httpClient);
                
                using (var response = await httpClient.GetAsync("https://localhost:44366/api/RelevantGames/" + game.ID))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    relGame = JsonConvert.DeserializeObject<RelevantGames>(apiResponse);
                }

                using (var response = await httpClient.GetAsync(APIUri))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    userList = JsonConvert.DeserializeObject<List<User>>(apiResponse);
                    user = userList.FirstOrDefault(u => u.Username == username);
                }
                UserRelevantGames games = new UserRelevantGames() { RelevantGamesID = relGame.ID, UserID = user.ID};
                StringContent content = new StringContent(JsonConvert.SerializeObject(games), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync(APIUri + user.ID + "/AddRelevantGame/", content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.Conflict)
                    {
                        return RedirectToAction("Index", "Home");
                    }
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    //relGame = JsonConvert.DeserializeObject<RelevantGames>(apiResponse);
                }
            }
            return RedirectToAction("UserList");
        }

        [HttpPost]
        public async Task<IActionResult> UserDeleteGame(int gameId)
        {
            List<User> userList = new List<User>();
            User user = new User();
            using (var httpClient = new HttpClient())
            {
                var username = PassTokenToHeader(httpClient);
                using(var response = await httpClient.GetAsync(APIUri))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    userList = JsonConvert.DeserializeObject<List<User>>(apiResponse);
                    user = userList.FirstOrDefault(u => u.Username == username);
                }
                using (var response = await httpClient.DeleteAsync(APIUri + user.ID + "/DeleteRelevantGame/" + gameId))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction("UserList");
        }



        public string PassTokenToHeader(HttpClient httpClient)
        {
            string username = "";
            var token = HttpContext.Request.Cookies.FirstOrDefault(c => c.Key == "jwtToken").Value;
            if (token != null)
            {
                JwtSecurityTokenHandler handler = new JwtSecurityTokenHandler();
                JwtSecurityToken tok = handler.ReadJwtToken(token);
                username = tok.Claims.FirstOrDefault(t => t.Type == "Username")?.Value;
                //ViewBag.Auth = username;
            }
            httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);
            return username;
        }
    }
}

GOSM/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GOSM</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue-grey.css">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Trirong">
    <style>
        body, content, h1, h2, h3, h4, h5{
            font-family: "Trirong", serif;
        }
    </style>
</head>
<body class="body">


    <header>

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-info border-bottom box-shadow mb-3">
            <div class="container">
                <div class="justify-content-center">
                    <svg width="80" height="80">
                        <circle cx="40" cy="40" r="30" stroke="yellow" stroke-width="4" fill="red" />
                        <text fill="#ffffff" font-size="12" font-family="Verdana" x="23" y="45">GOSM</text>
                    </svg>
                </div>
                
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GOSM</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @{
                            var cookies = Context.Request.Cookies.FirstOrDefault(c => c.Key == "Username");
                        }
                        @if (cookies.Value == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark " asp-area="" asp-controller="LoginView" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="LoginView" asp-action="Register">Register</a>
                            </li>

                        }

                        @if (cookies.Value == "admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="RelevantGamesView" asp-action="RelevantGamesList">Relevant Games</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserView" asp-action="UserList">User List</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PostView" asp-action="PostList">Posts</a>
                            </li>

                        }
                        else if (cookies.Value != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserView" asp-action="UserList">User List</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PostView" asp-action="PostList">Posts</a>
                            </li>

                        }
                    </ul>
                </div>
            </div>
        </nav>


    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <br />
            <br />
            <br />
            <br />
        </main>
    </div>

    <footer class="border-top footer text-muted position-absolute bg-info">
        <div class="container">
            <text class="text-black-50 text-b"><h3>&copy; 2020 - GOSM</h3></text>
            
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

    <script>
        // Used to toggle the menu on smaller screens when clicking on the menu button
        function openNav() {
            var x = document.getElementById("navDemo");
            if (x.className.indexOf("w3-show") == -1) {
                x.className += " w3-show";
            } else {
                x.className = x.className.replace(" w3-show", "");
            }
        }
    </script>
</body>
</html>